### ISSUE TITLE
navigate Pass data to ViewModel 

### ISSUE THREAD

**Issue by zyknow** [AvaloniaInside/Shell#11]
like maui shell,when ViewModel has IQueryAttributable,that can doing this
![image](https://github.com/AvaloniaInside/Shell/assets/49929368/9898e7d1-ef42-4c3d-b09f-b35cbb6a49e2)

but in Page ArgumentAsync method also can doing likeness function

so, i don't sure in this rep to Implement IQueryAttributable function is necessary

**Comment by zyknow** [comment]
and i think Maui QueryProperty is very useful ,but not only can use in Page, also can use in ViewModel
![image](https://github.com/AvaloniaInside/Shell/assets/49929368/4dfbfee4-cf59-4a1f-8989-ec8a388aab43)

**Comment by OmidID** [comment]
Hello @zyknow
Thanks for sharing the idea. I will take how it works and whether we can do it here or not.

**Comment by gentledepp** [comment]
I saw that there is a navigate overload in Navigator
`	Task NavigateAsync(string path, object? argument, CancellationToken cancellationToken = default);`

however, the argument is never passed to the target view.
Instead, the `OnNavigatingAsync` and `OnNavigateAsync` are only called on the page that is navigated away from.

Am I missing something, or is this a bug/intended?

I'd be willing to work on this feature, if you approve

**Comment by OmidID** [comment]
Hello @gentledepp 
You should use the method `ArgumentAsync` 
If you use `Page` class then override the method otherwise if you use your own base class then implement the `INavigationLifecycle` and you will have the `ArgumentAsync`

`OnNavigatingAsync` allow you to override the parameters of navigating or cancel the navigation. and `OnNavigateAsync` when navigation is over.

**Comment by OmidID** [comment]
As we do not have activity here for long time, I closing this issue
