### ISSUE TITLE
Call Appear after setting Argument

### ISSUE THREAD

**Issue by crobibero** [AvaloniaInside/Shell#7]
Looking at the source code `AppearAsync` is called before `ArgumentAsync`, so there isn't a way to initialize a ViewModel with the argument before showing the view.

My use-case: Navigate to a page with an item id, and while the view is appearing initialize the object that is related to the id.

I could change the logic to initialize the view model when the argument is set, but that would break the inheritance I have set up.

AppearAsync:
https://github.com/crobibero/jellyfin-client-maui/blob/master/src/Jellyfin.Avalonia/Views/Facades/BaseUserView.cs#L31-L37

ArgumentAsync
https://github.com/crobibero/jellyfin-client-maui/blob/master/src/Jellyfin.Avalonia/Views/ItemView.axaml.cs#L19-L27

**Comment by OmidID** [comment]
Hello @crobibero Thanks for the input.
I think is it a good idea that we call Argument after Appear or not. From one point of view, it is logical because Arguments can be executed on the same page instance. For example, if you have a page that navigates recursive itself with the type of `Top`, then the only event is the ArgumentAsync will call. 
I took a look at the Android Activity lifecycle and I noticed the OnActivityResult call after the OnCreate and Start, So we are not so far from one example. But I would like to know the behavior of Maui/Xamarin Shell to be more in sync with them. Basically, this library is designed for Maui/Xamarin devs to have an easy application ecosystem on Avalonia too. 
I can see on your app you have 2 versions of Maui and Avalonia. Would you please help me to understand the Maui Shell logic behind it?

Overall, For the MVVM pattern, this should be logical to update the VM based on the new argument after initializing.

But, Don't forget that you can change any part of Shell as you wish depending on your application. In case you implement your own `INavigationUpdateStrategy` you can change the whole logic of the lifecycle too. 

If you look at this block you can see Appear and Argument are not so far from each other.
https://github.com/AvaloniaInside/Shell/blob/main/src/AvaloniaInside.Shell/DefaultNavigationUpdateStrategy.cs#L47

Thanks again.

**Comment by crobibero** [comment]
The Maui app is likely going to be dropped in favor of Avalonia, and I was able to tweak my logic to recall my initialize function after the argument is set- so no more changes requested on your side!

Thanks again for the library
